version: '3.8'

services:
  # Development service
  notes-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - REACT_APP_APP_NAME=Notes App (Dev)
      - REACT_APP_VERSION=1.0.0-dev
      - CHOKIDAR_USEPOLLING=true
    networks:
      - notes-network
    profiles:
      - development

  # Production service
  notes-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - notes-network
    profiles:
      - production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (for production with backend)
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - notes-frontend-prod
    networks:
      - notes-network
    profiles:
      - production-with-proxy
    restart: unless-stopped

networks:
  notes-network:
    driver: bridge

volumes:
  node_modules: