version: '3.8'

services:
  notes-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=production-secret-key-here
      - DATABASE_URL=sqlite:///./notes.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
